[2024-12-04 17:19:42] INFO - train: Starting training process...
[2024-12-04 17:19:42] INFO - train: Loading configurations...
[2024-12-04 17:19:42] INFO - train: Using device: cuda
[2024-12-04 17:19:42] INFO - train: Creating data loaders...
[2024-12-04 17:19:42] ERROR - train: An error occurred: 'train'
Traceback (most recent call last):
  File "/nas2/jieui/class/deepnlp/project/scripts/train.py", line 50, in main
    batch_size=base_config['train']['batch_size']
KeyError: 'train'
