[2024-12-05 16:58:42] INFO - train: Starting training process...
[2024-12-05 16:58:42] INFO - train: Loading configurations...
[2024-12-05 16:58:42] INFO - train: Using device: cuda
[2024-12-05 16:58:42] INFO - train: Creating data loaders...
[2024-12-05 16:59:29] INFO - train: Setting up models and trainer...
[2024-12-05 16:59:29] INFO - train: Initializing context_aware distillation training...
[2024-12-05 16:59:33] INFO - train: Starting training...
[2024-12-05 16:59:34] ERROR - train: An error occurred: 'dict' object has no attribute 'training'
Traceback (most recent call last):
  File "/nas2/jieui/class/deepnlp/project/scripts/train.py", line 129, in main
    trainer.train()
  File "/nas2/jieui/class/deepnlp/project/src/trainers/base_trainer.py", line 72, in train
    loss = self._training_step(batch)
  File "/nas2/jieui/class/deepnlp/project/src/trainers/context_aware_distillation_trainer.py", line 91, in _training_step
    self.config.training.qa_loss_weight * qa_loss +
AttributeError: 'dict' object has no attribute 'training'
