[2024-12-05 17:01:14] INFO - train: Starting training process...
[2024-12-05 17:01:14] INFO - train: Loading configurations...
[2024-12-05 17:01:14] INFO - train: Using device: cuda
[2024-12-05 17:01:14] INFO - train: Creating data loaders...
[2024-12-05 17:01:56] INFO - train: Setting up models and trainer...
[2024-12-05 17:01:56] INFO - train: Initializing context_aware distillation training...
[2024-12-05 17:02:00] INFO - train: Starting training...
[2024-12-05 17:02:02] ERROR - train: An error occurred: 'dict' object has no attribute 'training'
Traceback (most recent call last):
  File "/nas2/jieui/class/deepnlp/project/scripts/train.py", line 129, in main
    trainer.train()
  File "/nas2/jieui/class/deepnlp/project/src/trainers/base_trainer.py", line 72, in train
    loss = self._training_step(batch)
  File "/nas2/jieui/class/deepnlp/project/src/trainers/context_aware_distillation_trainer.py", line 100, in _training_step
    if self.config.training.max_grad_norm > 0:
AttributeError: 'dict' object has no attribute 'training'
